CREATE DATABASE IF NOT EXIST CivilbridgeX
   CHARACTER SET utf8mb4
   COLLATE utf8mb4_unicode_ci;

USE CivilbridgeX;

CREATE TABLE users (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  full_name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NULL UNIQUE,
  phone VARCHAR(40) NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('HOME_BUILDER','STUDENT','ENGINEER','CONTRACTOR','SUPPLIER','ADMIN') NOT NULL,
  region_id BIGINT UNSIGNED NULL,
  is_verified TINYINT(1) NOT NULL DEFAULT 0,
  verification_status ENUM('UNVERIFIED','PENDING','VERIFIED','REJECTED') NOT NULL DEFAULT 'UNVERIFIED',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  last_login_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_users_role(role),
  INDEX idx_users_region(region_id)
) ENGINE=InnoDB;

CREATE TABLE user_profiles (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL UNIQUE,
  profession VARCHAR(120) NULL,
  company_name VARCHAR(160) NULL,
  address_text VARCHAR(255) NULL,
  bio TEXT NULL,
  avatar_url VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE audit_logs (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NULL,
  action VARCHAR(80) NOT NULL,              -- e.g. "LOGIN", "CREATE_PROJECT"
  entity_type VARCHAR(60) NULL,             -- e.g. "project", "listing"
  entity_id BIGINT UNSIGNED NULL,
  ip_address VARCHAR(64) NULL,
  user_agent VARCHAR(255) NULL,
  meta_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_audit_user(user_id),
  INDEX idx_audit_entity(entity_type, entity_id),
  CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE regions (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL UNIQUE,
  country VARCHAR(120) NOT NULL DEFAULT 'Rwanda',
  currency VARCHAR(20) NOT NULL DEFAULT 'RWF',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE region_multipliers (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  region_id BIGINT UNSIGNED NOT NULL,
  scope ENUM('MATERIAL','LABOR','TRANSPORT','OVERALL') NOT NULL,
  multiplier DECIMAL(10,4) NOT NULL DEFAULT 1.0000,
  active_from DATE NOT NULL,
  active_to DATE NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_mult_region(region_id),
  CONSTRAINT fk_mult_region FOREIGN KEY (region_id) REFERENCES regions(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE cost_catalog_items (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(60) NOT NULL UNIQUE,
  name VARCHAR(190) NOT NULL,
  category ENUM('FOUNDATION','STRUCTURE','ROOFING','FINISHES','PLUMBING','ELECTRICAL','LABOR','OTHER') NOT NULL,
  unit VARCHAR(40) NOT NULL,                  -- bag, m2, m3, day, kg...
  base_unit_cost DECIMAL(14,2) NOT NULL,
  default_wastage_percent DECIMAL(6,2) NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_catalog_category(category)
) ENGINE=InnoDB;

CREATE TABLE projects (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  project_name VARCHAR(160) NOT NULL,
  project_type ENUM('RESIDENTIAL','COMMERCIAL','INDUSTRIAL','INFRA') NOT NULL DEFAULT 'RESIDENTIAL',
  region_id BIGINT UNSIGNED NOT NULL,
  plot_size_m2 DECIMAL(10,2) NULL,
  built_area_m2 DECIMAL(10,2) NOT NULL,
  floors INT NOT NULL DEFAULT 1,
  bedrooms INT NULL,
  finish_level ENUM('BASIC','STANDARD','PREMIUM') NOT NULL DEFAULT 'STANDARD',
  structure_type ENUM('RC_FRAME','MASONRY','STEEL_FRAME') NOT NULL DEFAULT 'RC_FRAME',
  roof_type ENUM('IRON_SHEETS','TILES','CONCRETE','OTHER') NOT NULL DEFAULT 'IRON_SHEETS',
  status ENUM('DRAFT','ESTIMATED','DOCUMENTS','IN_PROGRESS','COMPLETED') NOT NULL DEFAULT 'DRAFT',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_projects_user(user_id),
  INDEX idx_projects_region(region_id),
  CONSTRAINT fk_projects_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_projects_region FOREIGN KEY (region_id) REFERENCES regions(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE estimate_summaries (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  project_id BIGINT UNSIGNED NOT NULL UNIQUE,
  estimated_total_cost DECIMAL(16,2) NOT NULL,
  cost_per_m2 DECIMAL(16,2) NOT NULL,
  risk_buffer_percent DECIMAL(6,2) NOT NULL DEFAULT 10.00,
  risk_buffer_amount DECIMAL(16,2) NOT NULL,
  final_estimated_cost DECIMAL(16,2) NOT NULL,
  assumptions_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_est_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE project_boq_items (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  project_id BIGINT UNSIGNED NOT NULL,
  catalog_item_id BIGINT UNSIGNED NULL,
  custom_name VARCHAR(190) NULL,
  category ENUM('FOUNDATION','STRUCTURE','ROOFING','FINISHES','PLUMBING','ELECTRICAL','LABOR','OTHER') NOT NULL,
  unit VARCHAR(40) NOT NULL,
  quantity DECIMAL(14,3) NOT NULL,
  unit_cost DECIMAL(14,2) NOT NULL,
  total_cost DECIMAL(16,2) NOT NULL,
  notes VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_boq_project(project_id),
  CONSTRAINT fk_boq_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_boq_catalog FOREIGN KEY (catalog_item_id) REFERENCES cost_catalog_items(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE project_documents (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  project_id BIGINT UNSIGNED NOT NULL,
  doc_type ENUM('PLAN_UPLOAD','BOQ_PDF','BOQ_EXCEL','FEASIBILITY_PDF','ESTIMATE_PDF','CARBON_PDF','ROI_PDF','PERMIT_FILE','OTHER') NOT NULL,
  file_url VARCHAR(255) NOT NULL,
  original_name VARCHAR(190) NULL,
  mime_type VARCHAR(120) NULL,
  file_size_bytes BIGINT UNSIGNED NULL,
  version INT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_docs_project(project_id),
  CONSTRAINT fk_docs_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE project_progress_logs (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  project_id BIGINT UNSIGNED NOT NULL,
  log_date DATE NOT NULL,
  stage ENUM('FOUNDATION','STRUCTURE','ROOFING','FINISHES','PLUMBING','ELECTRICAL','OTHER') NOT NULL,
  progress_percent DECIMAL(6,2) NOT NULL,
  amount_spent DECIMAL(16,2) NOT NULL DEFAULT 0,
  notes VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_progress_project(project_id),
  CONSTRAINT fk_progress_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE listings (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  listing_type ENUM('PROPERTY','LAND') NOT NULL,
  title VARCHAR(190) NOT NULL,
  description TEXT NULL,
  region_id BIGINT UNSIGNED NOT NULL,
  location_text VARCHAR(190) NULL,
  price DECIMAL(16,2) NULL,
  currency VARCHAR(20) NOT NULL DEFAULT 'RWF',
  size_m2 DECIMAL(12,2) NULL,
  bedrooms INT NULL,
  bathrooms INT NULL,
  zoning_info VARCHAR(190) NULL,     -- useful for land
  status ENUM('ACTIVE','SOLD','PENDING','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  owner_user_id BIGINT UNSIGNED NULL, -- if posted by a user/agent
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_listings_type(listing_type),
  INDEX idx_listings_region(region_id),
  CONSTRAINT fk_listings_region FOREIGN KEY (region_id) REFERENCES regions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_listings_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE listing_images (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  listing_id BIGINT UNSIGNED NOT NULL,
  image_url VARCHAR(255) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_listing_images(listing_id),
  CONSTRAINT fk_listing_images FOREIGN KEY (listing_id) REFERENCES listings(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE lead_requests (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  listing_id BIGINT UNSIGNED NOT NULL,
  requester_user_id BIGINT UNSIGNED NULL,
  name VARCHAR(120) NULL,
  phone VARCHAR(40) NULL,
  email VARCHAR(190) NULL,
  message TEXT NULL,
  request_type ENUM('MORE_INFO','SCHEDULE_VISIT','CONNECT_AGENT') NOT NULL,
  status ENUM('NEW','CONTACTED','CLOSED') NOT NULL DEFAULT 'NEW',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_leads_listing(listing_id),
  CONSTRAINT fk_leads_listing FOREIGN KEY (listing_id) REFERENCES listings(id) ON DELETE CASCADE,
  CONSTRAINT fk_leads_user FOREIGN KEY (requester_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE plans (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  category ENUM('RESIDENTIAL','COMMERCIAL','INDUSTRIAL','INFRA') NOT NULL,
  title VARCHAR(190) NOT NULL,
  style VARCHAR(120) NULL,                 -- modern, traditional, eco...
  description TEXT NULL,
  built_area_m2 DECIMAL(12,2) NOT NULL,
  floors INT NOT NULL DEFAULT 1,
  bedrooms INT NULL,
  is_verified TINYINT(1) NOT NULL DEFAULT 0,
  tier ENUM('FREE','PRO','PREMIUM') NOT NULL DEFAULT 'FREE',
  estimated_cost_min DECIMAL(16,2) NULL,
  estimated_cost_max DECIMAL(16,2) NULL,
  created_by_user_id BIGINT UNSIGNED NULL, -- architect/engineer who uploaded
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_plans_cat(category),
  CONSTRAINT fk_plans_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE plan_assets (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  plan_id BIGINT UNSIGNED NOT NULL,
  asset_type ENUM('RENDER','FLOOR_PLAN','STRUCTURAL','BROCHURE','OTHER') NOT NULL,
  file_url VARCHAR(255) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_plan_assets(plan_id),
  CONSTRAINT fk_plan_assets FOREIGN KEY (plan_id) REFERENCES plans(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE plan_requests (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  plan_id BIGINT UNSIGNED NOT NULL,
  requester_user_id BIGINT UNSIGNED NOT NULL,
  request_type ENUM('CUSTOMIZE','BUY_FULL_PACKAGE','ASK_EXPERT') NOT NULL,
  notes TEXT NULL,
  status ENUM('NEW','IN_REVIEW','ACCEPTED','REJECTED','COMPLETED') NOT NULL DEFAULT 'NEW',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_planreq_plan(plan_id),
  CONSTRAINT fk_planreq_plan FOREIGN KEY (plan_id) REFERENCES plans(id) ON DELETE CASCADE,
  CONSTRAINT fk_planreq_user FOREIGN KEY (requester_user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE service_providers (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL UNIQUE,
  provider_type ENUM('CONTRACTOR','SUPPLIER','ENGINEER','ARCHITECT') NOT NULL,
  business_name VARCHAR(160) NOT NULL,
  specialties_json JSON NULL,
  region_id BIGINT UNSIGNED NULL,
  verification_status ENUM('PENDING','VERIFIED','REJECTED') NOT NULL DEFAULT 'PENDING',
  avg_rating DECIMAL(4,2) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_provider_type(provider_type),
  CONSTRAINT fk_provider_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_provider_region FOREIGN KEY (region_id) REFERENCES regions(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE provider_reviews (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  provider_id BIGINT UNSIGNED NOT NULL,
  reviewer_user_id BIGINT UNSIGNED NOT NULL,
  rating INT NOT NULL,
  comment TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_reviews_provider(provider_id),
  CONSTRAINT fk_reviews_provider FOREIGN KEY (provider_id) REFERENCES service_providers(id) ON DELETE CASCADE,
  CONSTRAINT fk_reviews_user FOREIGN KEY (reviewer_user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE permit_requirements (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  region_id BIGINT UNSIGNED NOT NULL,
  project_type ENUM('RESIDENTIAL','COMMERCIAL','INDUSTRIAL','INFRA') NOT NULL,
  permit_name VARCHAR(190) NOT NULL,
  authority_name VARCHAR(190) NULL,
  estimated_fee DECIMAL(16,2) NULL,
  estimated_days INT NULL,
  steps_json JSON NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_permits_region(region_id),
  CONSTRAINT fk_permits_region FOREIGN KEY (region_id) REFERENCES regions(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE project_permit_tasks (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  project_id BIGINT UNSIGNED NOT NULL,
  permit_requirement_id BIGINT UNSIGNED NOT NULL,
  status ENUM('NOT_STARTED','IN_PROGRESS','SUBMITTED','APPROVED','REJECTED') NOT NULL DEFAULT 'NOT_STARTED',
  notes VARCHAR(255) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_project_permits(project_id),
  CONSTRAINT fk_ppt_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_ppt_req FOREIGN KEY (permit_requirement_id) REFERENCES permit_requirements(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE project_roi_reports (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  project_id BIGINT UNSIGNED NOT NULL UNIQUE,
  expected_rent_per_month DECIMAL(16,2) NULL,
  expected_sale_price DECIMAL(16,2) NULL,
  maintenance_per_year DECIMAL(16,2) NULL,
  vacancy_rate_percent DECIMAL(6,2) NOT NULL DEFAULT 0,
  roi_percent DECIMAL(8,3) NOT NULL,
  payback_years DECIMAL(8,3) NOT NULL,
  break_even_months INT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_roi_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE emission_factors (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  catalog_item_id BIGINT UNSIGNED NOT NULL UNIQUE,
  co2_per_unit DECIMAL(14,6) NOT NULL,
  unit VARCHAR(40) NOT NULL,
  source_note VARCHAR(255) NULL,
  active_from DATE NOT NULL,
  active_to DATE NULL,
  CONSTRAINT fk_em_catalog FOREIGN KEY (catalog_item_id) REFERENCES cost_catalog_items(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE project_carbon_summaries (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  project_id BIGINT UNSIGNED NOT NULL UNIQUE,
  total_co2_kg DECIMAL(16,3) NOT NULL,
  co2_per_m2 DECIMAL(16,3) NOT NULL,
  transport_distance_km DECIMAL(10,2) NULL,
  notes_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_carbon_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE ai_conversations (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(190) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_ai_conv_user(user_id),
  CONSTRAINT fk_ai_conv_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE ai_messages (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  conversation_id BIGINT UNSIGNED NOT NULL,
  role ENUM('USER','ASSISTANT','SYSTEM') NOT NULL,
  content TEXT NOT NULL,
  meta_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_ai_msg_conv(conversation_id),
  CONSTRAINT fk_ai_msg_conv FOREIGN KEY (conversation_id) REFERENCES ai_conversations(id) ON DELETE CASCADE
) ENGINE=InnoDB;

